/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o};
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"d":3,"ID":4,"P_COMA":5,"s":6,"declaracion_paquete":7,"declaracion_import":8,"declaracion_clase":9,"PACKAGE":10,"nombre_paquete":11,"declaracion_imports":12,"declaracion_import_lista":13,"IMPORT":14,"PUNTO":15,"modificadores_clase":16,"CLASS":17,"extender":18,"PAR_A":19,"instrucciones":20,"PAR_C":21,"EXTENDS":22,"modificador_clase":23,"PUBLIC":24,"FINAL":25,"modificadores_de_acceso":26,"PROTECTED":27,"PRIVATE":28,"instruccion":29,"declaracion_variable":30,"declaracion_funcion":31,"llamada_funcion":32,"asignacion":33,"imprimir":34,"imprimir_ln":35,"instruccion_if":36,"switch":37,"for":38,"while":39,"do_while":40,"continue":41,"break":42,"return":43,"declaracion_main":44,"FOR":45,"exp":46,"asignacion_para":47,"LLAVE_A":48,"LLAVE_C":49,"tipo_igual":50,"MAS_MAS":51,"MENOS_MENOS":52,"final":53,"tipo_variable_nativa":54,"def_variables":55,"tipo_variable_object":56,"lista_variables":57,"ASIGNACION":58,"COMA":59,"lista_parametros":60,"parametro":61,"lista_expresiones":62,"MAS_ASIGNACION":63,"MENOS_ASIGNACION":64,"STATIC":65,"VOID":66,"MAIN":67,"COR_A":68,"COR_C":69,"MENOS":70,"MAS":71,"POR":72,"DIV":73,"MOD":74,"MAYOR":75,"MENOR":76,"MAYOR_IGUAL":77,"MENOR_IGUAL":78,"IGUAL":79,"DIFERENTE":80,"AND":81,"OR":82,"NOT":83,"ENTERO":84,"DECIMAL":85,"TRUE":86,"FALSE":87,"CADENA":88,"CHAR_EXP":89,"llamada_funcion_exp":90,"BYTE":91,"SHORT":92,"INT":93,"LONG":94,"FLOAT":95,"DOUBLE":96,"CHAR":97,"BOOLEAN":98,"STRING":99,"if":100,"else":101,"lista_else_if":102,"IF":103,"ELSE":104,"else_if":105,"PRINT":106,"PRINTLN":107,"SWITCH":108,"lista_case":109,"case":110,"default":111,"CASE":112,"DOS_P":113,"DEFAULT":114,"WHILE":115,"DO":116,"CONTINUE":117,"BREAK":118,"RETURN":119,"$accept":0,"$end":1},
terminals_: {2:"error",4:"ID",5:"P_COMA",10:"PACKAGE",14:"IMPORT",15:"PUNTO",17:"CLASS",19:"PAR_A",21:"PAR_C",22:"EXTENDS",24:"PUBLIC",25:"FINAL",27:"PROTECTED",28:"PRIVATE",45:"FOR",48:"LLAVE_A",49:"LLAVE_C",51:"MAS_MAS",52:"MENOS_MENOS",58:"ASIGNACION",59:"COMA",63:"MAS_ASIGNACION",64:"MENOS_ASIGNACION",65:"STATIC",66:"VOID",67:"MAIN",68:"COR_A",69:"COR_C",70:"MENOS",71:"MAS",72:"POR",73:"DIV",74:"MOD",75:"MAYOR",76:"MENOR",77:"MAYOR_IGUAL",78:"MENOR_IGUAL",79:"IGUAL",80:"DIFERENTE",81:"AND",82:"OR",83:"NOT",84:"ENTERO",85:"DECIMAL",86:"TRUE",87:"FALSE",88:"CADENA",89:"CHAR_EXP",91:"BYTE",92:"SHORT",93:"INT",94:"LONG",95:"FLOAT",96:"DOUBLE",97:"CHAR",98:"BOOLEAN",99:"STRING",103:"IF",104:"ELSE",106:"PRINT",107:"PRINTLN",108:"SWITCH",112:"CASE",113:"DOS_P",114:"DEFAULT",115:"WHILE",116:"DO",117:"CONTINUE",118:"BREAK",119:"RETURN"},
productions_: [0,[3,2],[6,3],[6,1],[7,3],[8,1],[8,0],[12,2],[12,1],[13,3],[11,3],[11,1],[9,7],[18,2],[18,0],[16,2],[16,0],[23,1],[23,1],[26,1],[26,1],[26,1],[20,2],[20,1],[29,1],[29,1],[29,1],[29,1],[29,1],[29,1],[29,1],[29,1],[29,1],[29,1],[29,1],[29,1],[29,1],[29,1],[29,1],[38,10],[38,10],[47,3],[47,2],[47,2],[30,4],[30,3],[55,2],[57,3],[57,2],[57,1],[53,1],[53,0],[31,7],[31,8],[60,3],[60,1],[61,2],[61,2],[32,4],[32,5],[33,4],[33,3],[33,3],[50,1],[50,1],[50,1],[44,13],[46,2],[46,3],[46,3],[46,3],[46,3],[46,3],[46,3],[46,3],[46,3],[46,3],[46,3],[46,3],[46,3],[46,3],[46,3],[46,2],[46,1],[46,1],[46,1],[46,1],[46,1],[46,1],[46,1],[46,1],[90,3],[90,4],[62,3],[62,1],[62,3],[62,1],[54,1],[54,1],[54,1],[54,1],[54,1],[54,1],[54,1],[54,1],[54,1],[54,1],[56,1],[36,1],[36,2],[36,2],[36,3],[100,7],[101,4],[105,8],[102,2],[102,1],[34,5],[35,5],[37,7],[109,2],[109,1],[109,1],[109,2],[110,4],[111,3],[39,7],[40,9],[41,2],[42,2],[43,3],[43,2]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
}
},
table: [{3:1,4:[1,2]},{1:[3]},{5:[1,3]},{1:[2,1]}],
defaultActions: {3:[2,1]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

//Codigo JS para manejar el analizador lexico
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"case-sensitive":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:
break;
case 1:
break;
case 2:return "CLASS"
break;
case 3:return "EXTENDS"
break;
case 4:return "IMPORT"
break;
case 5:return "NEW"
break;
case 6:return "PACKAGE"
break;
case 7:return "SUPER"
break;
case 8:return "THIS"
break;
case 9:return "MAIN"
break;
case 10:return "PUBLIC"
break;
case 11:return "PRIVATE"
break;
case 12:return "PROTECTED"
break;
case 13:return "STATIC"
break;
case 14:return "FINAL"
break;
case 15:return "VOID"
break;
case 16:return "BYTE"
break;
case 17:return "SHORT"
break;
case 18:return "INT"
break;
case 19:return "LONG"
break;
case 20:return "FLOAT"
break;
case 21:return "DOUBLE"
break;
case 22:return "CHAR"
break;
case 23:return "BOOLEAN"
break;
case 24:return "STRING"
break;
case 25:return "NULL"
break;
case 26:return "BREAK"
break;
case 27:return "CONTINUE"
break;
case 28:return "RETURN"
break;
case 29:return "DO"
break;
case 30:return "FOR"
break;
case 31:return "WHILE"
break;
case 32:return "SWITCH"
break;
case 33:return "CASE"
break;
case 34:return "DEFAULT"
break;
case 35:return "ELSE"
break;
case 36:return "IF"
break;
case 37:return "PRINTLN"
break;
case 38:return "PRINT"
break;
case 39:return "DOS_P"
break;
case 40:return "P_COMA"
break;
case 41:return "COMA"
break;
case 42:return "MAS"
break;
case 43:return "MENOS"
break;
case 44:return "POR"
break;
case 45:return "DIV"
break;
case 46:return "MOD"
break;
case 47:return "ASIGNACION"
break;
case 48:return "MAS_ASIGNACION"
break;
case 49:return "MENOS_ASIGNACION"
break;
case 50:return "POR_ASIGNACION"
break;
case 51:return "DIV_ASIGNACION"
break;
case 52:return "MOD_ASIGNACION"
break;
case 53:return "IGUAL"
break;
case 54:return "DIFERENTE"
break;
case 55:return "MENOR"
break;
case 56:return "MAYOR"
break;
case 57:return "MENOR_IGUAL"
break;
case 58:return "MAYOR_IGUAL"
break;
case 59:return "AND"
break;
case 60:return "OR"
break;
case 61:return "NOT"
break;
case 62:return "MAS_MAS"
break;
case 63:return "MENOS_MENOS"
break;
case 64:return "LLAVE_A"
break;
case 65:return "LLAVE_C"
break;
case 66:return 'par_a'
break;
case 67:return "PAR_C"
break;
case 68:return "PUNTO"
break;
case 69:return "COR_A"
break;
case 70:return "COR_C"
break;
case 71:return "TRUE"
break;
case 72:return "FALSE"
break;
case 73: yy_.yytext = yy_.yytext.substr(0,yy_.yyleng-0); return 88; 
break;
case 74:return 89
break;
case 75:return 4
break;
case 76:return 85
break;
case 77:return 84
break;
case 78:/* Ignorar espacios en blanco y saltos de línea */
break;
case 79:return 'EOF'
break;
case 80:Parser.yy.Err.push(new Parser.yy.InsErr("Lexico",yy_.yylloc.first_line," en la columna: " + yy_.yylloc.first_column + ". Valor: " + yy_.yytext + ". No pertenece al lenguaje")); 
break;
}
},
rules: [/^(?:\\\/\\\/.*)/,/^(?:\\\/\\\*\(\[\^\*\]\|\(\\\*\+\[\^\*\/\]\)\)\*\\\*\+\\\/)/,/^(?:class\b)/,/^(?:extends\b)/,/^(?:import\b)/,/^(?:new\b)/,/^(?:package\b)/,/^(?:super\b)/,/^(?:this\b)/,/^(?:main\b)/,/^(?:public\b)/,/^(?:private\b)/,/^(?:protected\b)/,/^(?:static\b)/,/^(?:final\b)/,/^(?:void\b)/,/^(?:byte\b)/,/^(?:short\b)/,/^(?:int\b)/,/^(?:long\b)/,/^(?:float\b)/,/^(?:double\b)/,/^(?:char\b)/,/^(?:boolean\b)/,/^(?:String\b)/,/^(?:null\b)/,/^(?:break\b)/,/^(?:continue\b)/,/^(?:return\b)/,/^(?:do\b)/,/^(?:for\b)/,/^(?:while\b)/,/^(?:switch\b)/,/^(?:case\b)/,/^(?:default\b)/,/^(?:else\b)/,/^(?:if\b)/,/^(?:System\.out\.println\b)/,/^(?:System\.out\.print\b)/,/^(?::)/,/^(?:;)/,/^(?:,)/,/^(?:\+)/,/^(?:-)/,/^(?:\*)/,/^(?:\/)/,/^(?:%)/,/^(?:=)/,/^(?:\+=)/,/^(?:-=)/,/^(?:\*=)/,/^(?:\/=)/,/^(?:%=)/,/^(?:==)/,/^(?:!=)/,/^(?:<)/,/^(?:>)/,/^(?:<=)/,/^(?:>=)/,/^(?:&&)/,/^(?:\|\|)/,/^(?:!)/,/^(?:\+\+)/,/^(?:--)/,/^(?:\{)/,/^(?:\})/,/^(?:\()/,/^(?:\))/,/^(?:\.)/,/^(?:\[)/,/^(?:\])/,/^(?:true\b)/,/^(?:false\b)/,/^(?:"[^\"]*")/,/^(?:'[^]')/,/^(?:(()?[a-zA-Z]+(|[a-zA-Z0-9]+)*))/,/^(?:[0-9]+(\.[0-9]+)\b)/,/^(?:[0-9]+\b)/,/^(?:[ \t\n\r]+)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}